name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

env:
  RESOURCE_GROUP: conductor-test
  CONTAINER_GROUP: conductorregistry123
  WORKER_ENVIRONMENT_VARIABLES: ${{ secrets.WORKER_ENVIRONMENT_VARIABLES }}
  REGISTRY_LOGIN_SERVER: ${{ secrets.REGISTRY_LOGIN_SERVER }}
  REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  AZURE_LOCATION: ${{secrets.AZURE_LOCATION}}

jobs:
  run-ui-tests:
    name: Run UI tests
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.17.6-chrome100-ff98
    defaults:
      run:
        working-directory: ui
    steps:
      - name: Checkout Github Repo
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: yarn install

      - name: Build UI
        run: yarn run build

      - name: Run E2E Tests
        uses: cypress-io/github-action@v4
        with:
          working-directory: ui
          install: false
          start: yarn run serve-build
          wait-on: "http://localhost:5000"

  deploy:
    name: Push & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login To Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_LOGIN_SERVER }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}
      - run: |
          docker build -f docker/server/Dockerfile -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/conductor:${{ github.sha }} .
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/conductor:${{ github.sha }}

      - name: Deploy Conductor Worker to Azure Container Instance
        uses: Azure/aci-deploy@v1
        with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/conductor:${{ github.sha }}
          name: "conductorfromci"
          dns-name-label: ${{ env.RESOURCE_GROUP }}${{ github.run_number }}
          environment-variables: ${{ env.WORKER_ENVIRONMENT_VARIABLES }}
          secure-environment-variables: ${{ secrets.WORKER_SECURE_ENVIRONMENT_VARIABLES }}
          location: "west us"
          registry-login-server: ${{ env.REGISTRY_LOGIN_SERVER }}
          registry-username: ${{ env.REGISTRY_USERNAME }}
          registry-password: ${{ env.REGISTRY_PASSWORD }}
          restart-policy: Always
          cpu: 2
          memory: 4
          ports: 8080 80
